manifest:
  remotes:
    - name: zmk
      url-base: https://github.com/davidphilipbarr
  projects:
    - name: zmk
      remote: zmk
      revision: cradio-v2
      import: app/west.yml
  self:
    path: config
